"""Fit this station's harmonic baseline and write include/station_coeffs.h.

Same model and fitting as ml/sahasraksha/stream.py fit_coeffs(): 11 terms (mean, 3 daily
harmonics, 2 annual harmonics) per channel, robust IRLS least squares.

Input: any CSV with columns timestamp (UTC), T, P, RH. Use at least 14 days; a year is what
makes the annual terms meaningful. Two good sources:
  1. this rig's own log:   logs/verdicts_*.csv from tools/serial_logger.py (LIVE mode, 'pc_time' is local)
  2. the nearest real station from the notebook's NOAA data (hourly T/P/RH)

    pip install numpy pandas
    python tools/make_coeffs.py --csv logs/verdicts_20260925.csv --lon 88.36 --time-col pc_time --tz-offset-min 330
    then set HAVE_STATION_COEFFS 1 in include/config.h and rebuild.
"""
import argparse

import numpy as np
import pandas as pd


def design(lst, doy):
    cols = [np.ones_like(lst)]
    for k in (1, 2, 3):
        cols += [np.cos(2 * np.pi * k * lst / 24), np.sin(2 * np.pi * k * lst / 24)]
    cols += [np.cos(2 * np.pi * doy / 365.25), np.sin(2 * np.pi * doy / 365.25),
             np.cos(4 * np.pi * doy / 365.25), np.sin(4 * np.pi * doy / 365.25)]
    return np.column_stack(cols)


def fit(X, y, n_irls=6):
    ok = np.isfinite(y)
    b = np.linalg.lstsq(X[ok], y[ok], rcond=None)[0]
    for _ in range(n_irls):
        r = y[ok] - X[ok] @ b
        s = 1.4826 * np.median(np.abs(r - np.median(r))) + 1e-6
        w = np.sqrt(1.0 / (1.0 + (r / (2.5 * s)) ** 2))[:, None]
        b = np.linalg.lstsq(X[ok] * w, y[ok] * w.ravel(), rcond=None)[0]
    return b


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", required=True)
    ap.add_argument("--lon", type=float, required=True, help="station longitude, degrees E")
    ap.add_argument("--time-col", default="timestamp")
    ap.add_argument("--tz-offset-min", type=int, default=0, help="330 if the time column is IST")
    ap.add_argument("--out", default="include/station_coeffs.h")
    a = ap.parse_args()
    df = pd.read_csv(a.csv)
    ts = pd.to_datetime(df[a.time_col]) - pd.Timedelta(minutes=a.tz_offset_min)
    span_days = (ts.max() - ts.min()).total_seconds() / 86400
    lst = ((ts.dt.hour + ts.dt.minute / 60 + a.lon / 15) % 24).to_numpy(float)
    doy = ts.dt.dayofyear.to_numpy(float)
    X = design(lst, doy)
    lines = ["/* Generated by tools/make_coeffs.py from " + a.csv.replace("\\", "/") +
             f" ({len(df)} rows, {span_days:.1f} days). */",
             "#pragma once", '#include "sahasraksha_edge.h"', "static const sg_coeffs_t STATION_COEFFS = {{"]
    for ch in ("T", "P", "RH"):
        y = pd.to_numeric(df[ch], errors="coerce").to_numpy(float) if ch in df else np.full(len(df), np.nan)
        if np.isfinite(y).sum() < 100:
            b = np.zeros(11); b[0] = np.nanmedian(y) if np.isfinite(y).any() else 0.0
            print(f"{ch}: too little data, intercept only")
        else:
            if span_days < 300:     # annual terms cannot be estimated from < 1 year: keep them at 0
                b = np.zeros(11); b[:7] = fit(X[:, :7], y)
            else:
                b = fit(X, y)
            r = y - X @ b
            print(f"{ch}: residual std {np.nanstd(r):.3f} after fit")
        lines.append("  {" + ", ".join(f"{v:.6f}f" for v in b) + "},")
    lines.append("}};")
    open(a.out, "w").write("\n".join(lines) + "\n")
    if span_days < 300:
        print(f"note: {span_days:.0f} days of data -> annual terms left at 0 (daily cycle + mean only)")
    print("wrote", a.out, "-> set HAVE_STATION_COEFFS 1 in include/config.h and rebuild")


if __name__ == "__main__":
    main()
