import json, ast, sys
# usage: python tools/extract_core.py <final_notebook.ipynb> sahasraksha/core.py
# Cell numbers below refer to the final SIH26073 validation notebook (239 cells).
NB = sys.argv[1]
CELLS = [5, 23, 25, 27, 29, 124, 184, 186, 188]
WANT = """saturation_vapour_pressure dewpoint_from_T_RH RH_from_T_dewpoint reduce_to_msl heat_index
operator_label ingest_integrity physics_gates _run_length _design_matrix harmonic_residuals tide_heartbeat
cusum_features_v4 _haversine_km _neighbour_map _regional_agreement telemetry_checks
fit_score_models threshold_at_budget threshold_at_rate explain_row impute evaluate
maintenance_report impute_safe multivariate_consistency_checks silence_features
build_feature_frame_final_v3 fuse_v3 classify_root_cause_final calculate_severity
get_confidence_scores generate_work_orders classify_root_cause_v2 run_wmo_baseline_qc""".split()
nb = json.load(open(NB))
imports, consts, defs, order = [], {}, {}, []
for i in CELLS:
    s = ''.join(nb['cells'][i]['source'])
    s = "\n".join(l for l in s.splitlines() if not l.strip().startswith(("!", "%")))
    t = ast.parse(s)
    for n in t.body:
        seg = ast.get_source_segment(s, n)
        if isinstance(n, (ast.Import, ast.ImportFrom)):
            if seg not in imports: imports.append(seg)
        elif isinstance(n, (ast.FunctionDef, ast.ClassDef)) and n.name in WANT:
            if n.name not in order: order.append(n.name)
            defs[n.name] = (i, seg)
        elif isinstance(n, (ast.Assign, ast.AnnAssign)):
            tg = n.targets if isinstance(n, ast.Assign) else [n.target]
            nm = [x.id for x in tg if isinstance(x, ast.Name)]
            if nm and all(x.upper() == x for x in nm):
                for x in nm:
                    if x not in consts: consts[x] = (len(consts), i, seg)
                    else: consts[x] = (consts[x][0], i, seg)
out = ['"""Sahasraksha core — extracted verbatim from the final validation notebook.',
       '', 'Generated by tools/extract_core.py. Each function is the last definition the',
       'notebook uses for its final report (cells 5-191), so results match the notebook.',
       'Do not hand-edit: change the notebook and regenerate."""',
       'from __future__ import annotations', 'import warnings', 'warnings.filterwarnings("ignore")']
out += sorted(set(imports))
out.append("")
seen = set()
for k, (_, i, seg) in sorted(consts.items(), key=lambda kv: kv[1][0]):
    if seg in seen: continue
    seen.add(seg); out.append(f"# cell {i}\n{seg}")
out.append("")
for k in order:
    i, seg = defs[k]
    out.append(f"\n# ── from notebook cell {i} ──\n{seg}\n")
# operator actions (STEP 22 cell) and the alias the real-data cells use
import re
s232 = ''.join(nb['cells'][232]['source'])
m = re.search(r"^ACTIONS = \{.*?^\}", s232, re.S | re.M)
out.append("\n# ── operator actions, from the STEP 22 cell ──\n" + m.group(0))
out.append("\nfuse = fuse_v3   # notebook cell 29 alias; the real-data cells call fuse()")
open(sys.argv[2], "w").write("\n".join(out) + "\n")
print("defs", len(order), "consts", len(consts), "imports", len(imports))
