"""Sahasraksha core — extracted verbatim from the final validation notebook.

Generated by tools/extract_core.py. Each function is the last definition the
notebook uses for its final report (cells 5-191), so results match the notebook.
Do not hand-edit: change the notebook and regenerate."""
from __future__ import annotations
import warnings
warnings.filterwarnings("ignore")
from sklearn.covariance import MinCovDet
from sklearn.decomposition import PCA
from sklearn.ensemble import IsolationForest
from sklearn.isotonic import IsotonicRegression
from sklearn.metrics import brier_score_loss
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

# cell 5
MAGNUS_A = 17.62
# cell 5
MAGNUS_B = 243.12
# cell 5
E0 = 6.112
# cell 23
GROSS_LIMITS = {"T": (-40, 60), "P": (500, 1100), "RH": (0, 100)}
# cell 23
STEP_LIMITS = {"T": 6.0, "P": 5.0, "RH": 45.0}
# cell 124
CHANNELS = ["T", "P", "RH"]
# cell 23
DOMINANT_PERIOD = {"T": 24.0, "P": 12.0, "RH": 24.0}
# cell 23
FROZEN_MIN_RUN = {"T": 6, "P": 6, "RH": 10}
# cell 23
NATIONAL_T_MAX   = 52.0
# cell 23
DEWPOINT_CEILING = 34.0
# cell 23
MSL_RANGE  = (900.0, 1060.0)
# cell 23
Q_JUMP_MAX = 6.0
# cell 23
IMPOSSIBLE_GATES = ["gate_range_T", "gate_range_P", "gate_range_RH",
                    "gate_dewpoint", "gate_t_record", "gate_dewpoint_ceiling", "gate_msl_range"]
# cell 23
STRONG_IMPOSSIBLE = ["gate_t_record", "gate_dewpoint_ceiling", "gate_range_T", "gate_range_P", "gate_msl_range"]
# cell 25
REGIONAL_VETO = True
# cell 25
REGIONAL_MIN_NEIGHBOURS = 2
# cell 29
FEATURES = (
    [f"z_{c}" for c in CHANNELS]
    + [f"d_{c}" for c in CHANNELS]
    + [f"runlen_{c}" for c in CHANNELS]
    + [f"amp_ratio_{c}" for c in CHANNELS]
    + [f"phase_dev_{c}" for c in CHANNELS]
    + [f"rollstd_ratio_{c}" for c in CHANNELS]
    + [f"cusum_slow_{c}" for c in CHANNELS]   # UPGRADED
    + [f"cusum_fast_{c}" for c in CHANNELS]   # UPGRADED
    + ["dewpoint_depression", "comms_partial", "comms_silent", "silent_hours"]
)
# cell 29
ROOT_CAUSE_RULES = [
    # (name, predicate over a single row of F)
    ("dropout",  lambda r: r["gate_missing"] == 1),
    ("frozen",   lambda r: max(r["runlen_T"], r["runlen_P"], r["runlen_RH"]) >= 4),
    ("spike",    lambda r: max(abs(r["z_T"]), abs(r["z_P"]), abs(r["z_RH"])) > 6
                 and max(r["d_T"] / 6.0, r["d_P"] / 5.0, r["d_RH"] / 45.0) > 0.8),
    ("noise",    lambda r: max(r["rollstd_ratio_T"], r["rollstd_ratio_P"],
                               r["rollstd_ratio_RH"]) > 3.0),
    ("sluggish", lambda r: min(r["amp_ratio_T"], r["amp_ratio_P"],
                               r["amp_ratio_RH"]) < 0.70),
    ("drift",    lambda r: max(r["cusum_T"], r["cusum_P"], r["cusum_RH"]) > 8.0),
]


# ── from notebook cell 5 ──
def saturation_vapour_pressure(T):
    """Saturation vapour pressure e_s(T) in hPa. T in degrees C."""
    return E0 * np.exp(MAGNUS_A * T / (MAGNUS_B + T))


# ── from notebook cell 5 ──
def dewpoint_from_T_RH(T, RH):
    """
    Dewpoint temperature (deg C) from air temperature and relative humidity.

    Physical law: dewpoint can never exceed air temperature. Any station
    reporting Td > T is emitting an impossible observation. This gives us a
    detector with ~100% precision that requires zero training data.
    """
    RH = np.clip(RH, 1e-3, None)
    gamma = np.log(RH / 100.0) + MAGNUS_A * T / (MAGNUS_B + T)
    return MAGNUS_B * gamma / (MAGNUS_A - gamma)


# ── from notebook cell 5 ──
def RH_from_T_dewpoint(T, Td):
    """Relative humidity (%) from air temperature and dewpoint."""
    return 100.0 * saturation_vapour_pressure(Td) / saturation_vapour_pressure(T)


# ── from notebook cell 5 ──
def reduce_to_msl(P_station, T, altitude_m):
    """
    Reduce station-level pressure to mean sea level so that stations at
    different altitudes become directly comparable.

    Without this step a spatial consistency check is meaningless: a hill
    station legitimately reads ~100 hPa below a coastal one.
    """
    T_kelvin = T + 273.15
    return P_station * np.exp(9.80665 * altitude_m / (287.05 * T_kelvin))


# ── from notebook cell 5 ──
def heat_index(T, RH):
    """
    Rothfusz heat index in deg C -- the apparent temperature a human feels.

    This is the bridge to problem statement 26083 (Extreme Heatwave Early
    Warning and Human Thermal Stress Index). It is computed from exactly the
    two channels Sahasraksha already validates, which is precisely why sensor
    quality is a public-health question and not just a data-hygiene one.
    """
    Tf = T * 9.0 / 5.0 + 32.0
    HI = (-42.379 + 2.04901523 * Tf + 10.14333127 * RH
          - 0.22475541 * Tf * RH - 6.83783e-3 * Tf ** 2
          - 5.481717e-2 * RH ** 2 + 1.22874e-3 * Tf ** 2 * RH
          + 8.5282e-4 * Tf * RH ** 2 - 1.99e-6 * Tf ** 2 * RH ** 2)
    # Below ~80 F the polynomial is not valid; fall back to a simple average
    simple = 0.5 * (Tf + 61.0 + (Tf - 68.0) * 1.2 + RH * 0.094)
    HI = np.where(Tf < 80.0, simple, HI)
    return (HI - 32.0) * 5.0 / 9.0


# ── from notebook cell 23 ──
def operator_label(F, mechanism):
    """What an operator sees. A physically impossible VALUE is named as such;
    otherwise the MECHANISM. Root-cause precision is scored on `mechanism` only."""
    cols = [g for g in STRONG_IMPOSSIBLE if g in F.columns]
    imp = F[cols].to_numpy().max(axis=1) == 1 if cols else np.zeros(len(F), bool)
    lab = np.where(imp, "impossible", np.asarray(mechanism, dtype=object))
    ts_bad = (F["gate_timestamp"].to_numpy() == 1) if "gate_timestamp" in F.columns else np.zeros(len(F), bool)
    return np.where(ts_bad & ~imp, "corrupt", lab)


# ── from notebook cell 23 ──
def ingest_integrity(df):
    """Check ARRIVAL order before anything re-sorts it: a record whose timestamp is
    not later than every earlier record of its station is a duplicate or arrived
    out of order. Then give the time-series layers a clean, time-ordered copy,
    carrying the verdict along as `ingest_bad`."""
    ts = pd.to_datetime(df["timestamp"])
    prev_max = ts.groupby(df["station_id"]).cummax().groupby(df["station_id"]).shift()
    bad = (ts <= prev_max).fillna(False).to_numpy()
    return (df.assign(ingest_bad=bad.astype(int))
              .sort_values(["station_id", "timestamp"], kind="stable").reset_index(drop=True))


# ── from notebook cell 23 ──
def physics_gates(df, station_cadence=None):
    g = pd.DataFrame(index=df.index)
    T, P, RH = df["T"].to_numpy(), df["P"].to_numpy(), df["RH"].to_numpy()

    # Cadence CANNOT be measured from timestamp gaps on a reindexed grid —
    # every station shows 1-hour gaps there regardless of true reporting
    # rate, once interpolation has filled the intermediate rows. It must be
    # supplied from outside, computed on non-interpolated data.
    if station_cadence is None:
        step_scale = np.ones(len(df))
    else:
        step_scale = df["station_id"].map(station_cadence).fillna(1.0).to_numpy()

    for ch, arr in zip(CHANNELS, [T, P, RH]):
        lo, hi = GROSS_LIMITS[ch]
        g[f"gate_range_{ch}"] = ((arr < lo) | (arr > hi)).astype(int)

    with np.errstate(invalid="ignore", divide="ignore"):
        Td = dewpoint_from_T_RH(T, np.clip(RH, 0.1, None))
    g["dewpoint"] = Td
    g["dewpoint_depression"] = T - Td
    g["gate_dewpoint"] = ((Td > T + 0.5) | (RH > 100.5)).astype(int)
    g["gate_t_record"]         = (T  > NATIONAL_T_MAX).astype(int)
    g["gate_dewpoint_ceiling"] = (Td > DEWPOINT_CEILING).astype(int)
    # ── Multivariate consistency: T, P and RH checked TOGETHER ──
    # (1) Hydrostatic: station P reduced to sea level with the station's own T and
    #     altitude must fall inside the physical band of Indian sea-level pressure.
    if "alt_m" in df.columns:
        with np.errstate(invalid="ignore", over="ignore"):
            P_msl = reduce_to_msl(P, T, df["alt_m"].to_numpy(dtype=float))
        g["P_msl"] = P_msl
        g["gate_msl_range"] = ((P_msl < MSL_RANGE[0]) | (P_msl > MSL_RANGE[1])).astype(int)
    # (2) Moisture budget: water content (specific humidity) needs Td AND P. RH may
    #     swing with temperature, but the air's actual water content cannot jump
    #     several g/kg between two reports unless a front passes.
    _alt = df["alt_m"].to_numpy(dtype=float) if "alt_m" in df.columns else np.zeros(len(df))
    P_eff = np.where(np.isfinite(P), P, 1013.25 * np.exp(-_alt / 8434.0))
    with np.errstate(invalid="ignore", over="ignore"):
        e_v = 6.112 * np.exp(17.67 * Td / (Td + 243.5))
        q = 622.0 * e_v / (P_eff - 0.378 * e_v)                    # g/kg
    g["q_gkg"] = q
    dq = pd.Series(q, index=df.index).groupby(df["station_id"]).diff().abs().to_numpy()
    g["d_q"] = np.nan_to_num(dq)
    g["gate_moisture_jump"] = (np.nan_to_num(dq) > Q_JUMP_MAX * np.sqrt(step_scale)).astype(int)
    # (3) Data integrity: each record must arrive once, in time order.
    if "ingest_bad" in df.columns:                      # verdict from ingest_integrity()
        g["gate_timestamp"] = df["ingest_bad"].to_numpy().astype(int)
    elif "timestamp" in df.columns:
        _ts = pd.to_datetime(df["timestamp"])
        _dt = _ts.groupby(df["station_id"]).diff()
        g["gate_timestamp"] = (_dt <= pd.Timedelta(0)).fillna(False).astype(int).to_numpy()

    for ch in CHANNELS:
        d = df.groupby("station_id", observed=True)[ch].diff().abs().to_numpy()
        g[f"d_{ch}"] = np.nan_to_num(d)
        g[f"gate_step_{ch}"] = (np.nan_to_num(d) > STEP_LIMITS[ch]*np.sqrt(step_scale)).astype(int)

    hourly_only = (step_scale <= 1.0)
    for ch in CHANNELS:
        g[f"runlen_{ch}"] = _run_length(df, ch)
        run_hours = g[f"runlen_{ch}"] * step_scale
        # Frozen-run detection empirically has zero precision at every
        # threshold >=12h, for ALL THREE channels, on 3-hourly ISD stations
        # (341,668 obs tested; T, RH and P swept independently, same result
        # each time). The signature is valid for hourly-cadence reporting
        # only (e.g. AWS_HYD) and is disabled at coarser cadence.
        g[f"gate_frozen_{ch}"] = ((run_hours >= FROZEN_MIN_RUN[ch]) & hourly_only).astype(int)

    # A channel counts as 'missing' only if this station normally reports it.
    # A station with no barometer (e.g. AWS_BLR, AWS_SHL) is not failing every hour.
    _avail = df[CHANNELS].notna().groupby(df["station_id"]).transform("mean")
    g["gate_missing"] = (df[CHANNELS].isna() & (_avail >= 0.5)).any(axis=1).astype(int)

    gate_cols = [c for c in g.columns
                 if c.startswith("gate_") and c != "gate_missing"]
    g["physics_flag"] = (g[gate_cols].sum(axis=1) > 0).astype(int)
    return g


# ── from notebook cell 23 ──
def _run_length(df, ch):
    """Consecutive-identical-value run length, computed per station."""
    out = np.zeros(len(df))
    for _, idx in df.groupby("station_id", observed=True).indices.items():
        v = df[ch].to_numpy()[idx]
        run = np.zeros(len(v))
        c = 0
        for i in range(1, len(v)):
            if not np.isnan(v[i]) and v[i] == v[i - 1]:
                c += 1
            else:
                c = 0
            run[i] = c
        out[idx] = run
    return out


# ── from notebook cell 23 ──
def _design_matrix(lst, doy, n_diurnal=3, annual=True):
    cols = [np.ones_like(lst)]
    for k in range(1, n_diurnal + 1):
        cols += [np.cos(2 * np.pi * k * lst / 24.0),
                 np.sin(2 * np.pi * k * lst / 24.0)]
    if annual:
        cols += [np.cos(2 * np.pi * doy / 365.25),
                 np.sin(2 * np.pi * doy / 365.25),
                 np.cos(4 * np.pi * doy / 365.25),
                 np.sin(4 * np.pi * doy / 365.25)]
    return np.column_stack(cols)


# ── from notebook cell 23 ──
def harmonic_residuals(df, train_frac=1.0, n_irls=6):
    """
    Fit each station's own climatological signature (diurnal harmonics +
    annual cycle) on an early training slice, then measure how far every
    later observation sits from that signature.

    The fit is done with iteratively reweighted least squares so that faults
    present in the training window cannot capture the model.
    """
    res = pd.DataFrame(index=df.index)
    lst_all = ((df["timestamp"].dt.hour + df["timestamp"].dt.minute / 60.0)
               + df["lon"] / 15.0) % 24.0
    doy_all = df["timestamp"].dt.dayofyear.to_numpy().astype(float)
    res["lst"] = lst_all.to_numpy()

    for ch in CHANNELS:
        fitted = np.full(len(df), np.nan)
        for _, idx in df.groupby("station_id", observed=True).indices.items():
            y = df[ch].to_numpy()[idx].astype(float)
            X = _design_matrix(lst_all.to_numpy()[idx], doy_all[idx])
            ntr = len(idx) if train_frac >= 1.0 else max(int(len(idx) * train_frac), 200)
            Xtr, ytr = X[:ntr], y[:ntr]
            ok = np.isfinite(ytr)
            if ok.sum() < 50:
                continue
            beta = np.linalg.lstsq(Xtr[ok], ytr[ok], rcond=None)[0]
            for _ in range(n_irls):                  # robust reweighting
                r = ytr[ok] - Xtr[ok] @ beta
                s = 1.4826 * np.median(np.abs(r - np.median(r))) + 1e-6
                w = 1.0 / (1.0 + (r / (2.5 * s)) ** 2)
                W = np.sqrt(w)[:, None]
                beta = np.linalg.lstsq(Xtr[ok] * W, ytr[ok] * W.ravel(),
                                       rcond=None)[0]
            fitted[idx] = X @ beta
        res[f"fit_{ch}"] = fitted
        res[f"resid_{ch}"] = df[ch].to_numpy() - fitted

    # --- spatial consistency ------------------------------------------
    # Weather is shared between neighbours; a sensor fault is not. Removing
    # the network-median residual removes the weather and leaves the fault.
    res["timestamp"] = df["timestamp"].to_numpy()
    nbrs, isolated_stations = _neighbour_map(df, radius_km=700.0)
    res["spatial_mode"] = np.where(
        df["station_id"].isin(isolated_stations).to_numpy(), "isolated", "network")
    for ch in CHANNELS:
        if isolated_stations:
            # Each station compares only against its own within-radius
            # neighbours, not the whole network. An isolated station skips
            # spatial subtraction entirely -- z_ch falls back to the
            # temporal residual alone, flagged via spatial_mode so it is
            # auditable rather than silently degraded.
            tmp = res.assign(_sid=df["station_id"].to_numpy())
            med = np.zeros(len(df))
            for sid, idx in df.groupby("station_id", observed=True).indices.items():
                if sid in isolated_stations:
                    med[idx] = 0.0
                    continue
                nb_ids = nbrs[sid]
                mask = tmp["_sid"].isin(nb_ids).to_numpy()
                nb_by_time = (tmp.loc[mask].groupby("timestamp")[f"resid_{ch}"]
                              .median())
                med[idx] = tmp.loc[idx, "timestamp"].map(nb_by_time).fillna(0.0).to_numpy()
            res[f"sresid_{ch}"] = res[f"resid_{ch}"] - med
        else:
            med = res.groupby("timestamp", observed=True)[f"resid_{ch}"].transform("median")
            res[f"sresid_{ch}"] = res[f"resid_{ch}"] - med

    # Robust standardisation, per station, using the training slice only
    for ch in CHANNELS:
        z = np.zeros(len(df))
        for _, idx in df.groupby("station_id", observed=True).indices.items():
            v = res[f"sresid_{ch}"].to_numpy()[idx]
            base = v[np.isfinite(v)]
            s = 1.4826 * np.median(np.abs(base - np.median(base))) + 1e-6
            z[idx] = (v - np.median(base)) / s
        res[f"z_{ch}"] = z

    res["regional_event"] = _regional_agreement(res, df, nbrs)
    res = res.drop(columns=["timestamp"])
    return res


# ── from notebook cell 23 ──
def tide_heartbeat(df, resid, window_hours=72, min_coverage=0.75):
    # A 12-hour harmonic needs more than four samples per cycle. Stations
    # reporting three-hourly hit exactly the Nyquist minimum and the fit
    # collapses — measured: lift 9.37 on hourly stations, 0.00 on 3-hourly.
    # Refuse to emit a degradation score we cannot support.
    _cad = df.groupby("station_id")["timestamp"].apply(lambda s: s.dt.hour.nunique())
    TIDE_CAPABLE = set(_cad[_cad >= 12].index)
    out = pd.DataFrame(index=df.index)
    lst = resid["lst"].to_numpy()
    for ch in CHANNELS:
        period = DOMINANT_PERIOD[ch]
        amp = np.full(len(df), np.nan); pha = np.full(len(df), np.nan)
        c = np.cos(2*np.pi*lst/period); s = np.sin(2*np.pi*lst/period)
        y_all = df[ch].to_numpy().astype(float)
        for _, idx in df.groupby("station_id", observed=True).indices.items():
            y = pd.Series(y_all[idx])
            # Refuse to fit a harmonic to a window that is mostly holes.
            cov_w = y.notna().rolling(window_hours, min_periods=1).mean().to_numpy()
            y_dt = y - y.rolling(window_hours, min_periods=12).mean()
            A = 2*(y_dt*c[idx]).rolling(window_hours, min_periods=36).mean().to_numpy()
            B = 2*(y_dt*s[idx]).rolling(window_hours, min_periods=36).mean().to_numpy()
            ok = cov_w >= min_coverage
            amp[idx] = np.where(ok, np.sqrt(A**2+B**2), np.nan)
            pha[idx] = np.where(ok, np.arctan2(B, A), np.nan)
        out[f"amp_{ch}"], out[f"phase_{ch}"] = amp, pha

        ratio = np.full(len(df), np.nan); pdev = np.full(len(df), np.nan)
        for _, idx in df.groupby("station_id", observed=True).indices.items():
            a = amp[idx]
            if np.isfinite(a).sum() < 48:      # no baseline -> no opinion
                continue
            ratio[idx] = a / (np.nanmedian(a) + 1e-9)
            bp = np.nanmedian(pha[idx])
            pdev[idx] = np.abs(np.angle(np.exp(1j*(pha[idx]-bp))))
        out[f"amp_ratio_{ch}"] = ratio        # NaN stays NaN — no fake health
        out[f"phase_dev_{ch}"] = pdev

    # Pressure only. The semidiurnal tide is stable year-round; the diurnal
    # ranges of T and RH are not — they halve under monsoon cloud. Taking
    # min() across all three channels made this fire on the rains for four
    # months a year, which is why it scored below chance.
    deg = np.zeros(len(df)); ratio_P = np.full(len(df), np.nan)
    for sid, idx in df.groupby("station_id", observed=True).indices.items():
        if sid not in TIDE_CAPABLE:
            continue          # cadence cannot resolve S2; stay silent
        a = pd.Series(out["amp_P"].to_numpy()[idx])
        if np.isfinite(a.to_numpy()).sum() < 24*14:
            continue
        base = a.rolling(24*30, min_periods=24*7).median()
        r = (a / base).to_numpy()
        ratio_P[idx] = r
        deg[idx] = np.where(np.isfinite(r), np.clip(1-np.clip(r,0,1), 0, 1), 0.0)
    out["amp_ratio_P_seasonal"] = ratio_P
    out["heartbeat_health"] = np.clip(1-deg, 0, 1)
    out["degradation_index"] = deg
    return out


# ── from notebook cell 184 ──
def cusum_features_v4(resid, df, k_slow=3.0, h_slow=8.0, k_fast=3.0, h_fast=12.0):
    out = pd.DataFrame(index=df.index)
    out["cusum_flag"] = 0
    
    for ch in ["T", "P", "RH"]:
        z_all = resid[f"z_{ch}"].to_numpy()
        fast_stat = np.zeros(len(df))
        slow_stat = np.zeros(len(df))
        ewma_bias = np.zeros(len(df))
        cusum_flag = np.zeros(len(df), dtype=int)
        
        for _, idx in df.groupby("station_id", observed=True).indices.items():
            z = np.nan_to_num(z_all[idx])
            n = len(z)
            cp_fast, cn_fast = 0.0, 0.0
            cp_slow, cn_slow = 0.0, 0.0
            ewma = 0.0
            alpha = 0.05
            latched = False
            
            for i in range(n):
                v = z[i]
                ewma = (1 - alpha) * ewma + alpha * v
                ewma_bias[idx[i]] = ewma
                
                cp_fast = min(max(0.0, cp_fast + v - k_fast), 2.0 * h_fast)
                cn_fast = min(max(0.0, cn_fast - v - k_fast), 2.0 * h_fast)
                fast_stat[idx[i]] = max(cp_fast, cn_fast)
                
                cp_slow = min(max(0.0, cp_slow + v - k_slow), 2.0 * h_slow)
                cn_slow = min(max(0.0, cn_slow - v - k_slow), 2.0 * h_slow)
                slow_stat[idx[i]] = max(cp_slow, cn_slow)
                
                # Hysteresis Latching Logic (matched to validated cusum_features_v3)
                if fast_stat[idx[i]] > h_fast or slow_stat[idx[i]] > h_slow:
                    latched = True
                elif fast_stat[idx[i]] < (h_fast / 3.0) and slow_stat[idx[i]] < (h_slow / 3.0):
                    latched = False
                    
                cusum_flag[idx[i]] = 1 if latched else 0
                
        out[f"cusum_fast_{ch}"] = fast_stat
        out[f"cusum_slow_{ch}"] = slow_stat
        out[f"ewma_bias_{ch}"] = ewma_bias
        out[f"cusum_flag_{ch}"] = cusum_flag
        out["cusum_flag"] = (out["cusum_flag"] | cusum_flag)
        
    return out


# ── from notebook cell 25 ──
def _haversine_km(lat1, lon1, lat2, lon2):
    R = 6371.0
    la1, la2 = np.radians(lat1), np.radians(lat2)
    dlat = np.radians(lat2 - lat1); dlon = np.radians(lon2 - lon1)
    a = np.sin(dlat/2)**2 + np.cos(la1)*np.cos(la2)*np.sin(dlon/2)**2
    return 2*R*np.arcsin(np.sqrt(a))


# ── from notebook cell 25 ──
def _neighbour_map(df, radius_km=700.0):
    """Which stations does each station actually have a weather-sharing
    relationship with? IMD has genuinely isolated stations (Leh, high
    Himalaya) where a network-median spatial check has nothing to compare
    against -- silently falling back to the full-network median there
    compares a mountain station against the coastal plains and calls the
    disagreement a fault."""
    meta = df.groupby("station_id", observed=True)[["lat","lon"]].first()
    ids = meta.index.to_list()
    n = len(ids)
    D = np.zeros((n, n))
    for i in range(n):
        D[i] = _haversine_km(meta.lat.iloc[i], meta.lon.iloc[i],
                             meta.lat.to_numpy(), meta.lon.to_numpy())
    nbrs, isolated = {}, []
    for i, sid in enumerate(ids):
        within = [ids[j] for j in range(n) if j != i and D[i, j] <= radius_km]
        nbrs[sid] = within
        if not within:
            isolated.append(sid)
    return nbrs, isolated


# ── from notebook cell 25 ──
def _regional_agreement(res, df, nbrs, z_min=2.0, ratio=0.5):
    """For every row: do at least REGIONAL_MIN_NEIGHBOURS neighbours (within 700 km)
    show the SAME departure at the SAME time -- same sign, at least half the size,
    on the channel where this station departs most? A depression, a heat wave or a
    cold wave moves a whole region together; a failing sensor moves alone."""
    sid = df["station_id"].to_numpy(); ts = pd.to_datetime(df["timestamp"]).to_numpy()
    key = pd.MultiIndex.from_arrays([ts, sid])
    agree, zabs = [], []
    for ch in CHANNELS:
        z = res[f"z_{ch}"].to_numpy()
        wide = (pd.DataFrame({"ts": ts, "sid": sid, "z": z})
                  .groupby(["ts", "sid"])["z"].first().unstack())
        W = wide.to_numpy(); cols = list(wide.columns); pos = {c: i for i, c in enumerate(cols)}
        A = np.zeros_like(W)
        with np.errstate(invalid="ignore"):
            for c in cols:
                nb = [pos[n] for n in nbrs.get(c, []) if n in pos]
                if not nb:
                    continue
                zs = W[:, [pos[c]]]; zn = W[:, nb]
                ok = (np.sign(zn) == np.sign(zs)) & (np.abs(zn) >= ratio * np.abs(zs)) & (np.abs(zs) >= z_min)
                A[:, pos[c]] = ok.sum(axis=1)
        agree.append(pd.DataFrame(A, index=wide.index, columns=cols).stack().reindex(key).to_numpy())
        zabs.append(np.abs(np.nan_to_num(z)))
    dom = np.argmax(np.vstack(zabs), axis=0)                      # channel this station departs most on
    n_agree = np.nan_to_num(np.vstack(agree))[dom, np.arange(len(df))]
    return (n_agree >= REGIONAL_MIN_NEIGHBOURS).astype(int)


# ── from notebook cell 27 ──
def telemetry_checks(df, gap_multiple=2.5):
    """
    Separates COMMUNICATION failure from SENSOR failure -- a different
    mechanism from gate_missing (only sees a NaN row) and from a single-
    channel frozen gate (can be one stuck sensor with a healthy link).
    Two independent signatures:
      1. a timestamp gap far longer than the station's normal cadence
      2. ALL THREE channels frozen on the exact same run simultaneously
         (a stuck datalogger, not one failed sensor)
    """
    out = pd.DataFrame(index=df.index)
    out["comms_gap"] = 0
    out["comms_stuck_logger"] = 0

    for sid, idx in df.groupby("station_id", observed=True).indices.items():
        ts = df["timestamp"].to_numpy()[idx]
        if len(ts) > 2:
            dt = np.diff(ts).astype("timedelta64[m]").astype(float)
            typical = np.median(dt[dt > 0]) if (dt > 0).any() else 60.0
            gap = np.concatenate([[False], dt > gap_multiple * typical])
            out.iloc[idx[gap], out.columns.get_loc("comms_gap")] = 1

        sub = df.iloc[idx][CHANNELS]
        same_all = (sub.diff().abs().fillna(1) < 1e-9).all(axis=1)
        run = np.zeros(len(sub), dtype=int); c = 0
        for i, v in enumerate(same_all.to_numpy()):
            c = c + 1 if v else 0
            run[i] = c
        out.iloc[idx[run >= 3], out.columns.get_loc("comms_stuck_logger")] = 1

    out["comms_error"] = ((out.comms_gap == 1) | (out.comms_stuck_logger == 1)).astype(int)
    return out


# ── from notebook cell 184 ──
def multivariate_consistency_checks(df, window_h=24):
    out = pd.DataFrame(index=df.index)
    out["multivar_consistency_flag"] = 0
    out["tamper_flag"] = 0
    out["wbgt_shade"] = 0.0
    
    for sid, idx in df.groupby("station_id", observed=True).indices.items():
        sub_df = df.iloc[idx].copy()
        T = sub_df["T"].to_numpy()
        RH = sub_df["RH"].to_numpy()
        
        t_series = pd.Series(T)
        rh_series = pd.Series(RH)
        rolling_corr = t_series.rolling(window=window_h, min_periods=12).corr(rh_series).fillna(0.0).to_numpy()
        out.iloc[idx, out.columns.get_loc("multivar_consistency_flag")] = (rolling_corr > 0.40).astype(int)
        
        dT_dt = np.abs(np.concatenate([[0.0], np.diff(T)]))
        dRH_dt = np.abs(np.concatenate([[0.0], np.diff(RH)]))
        tamper = ((dT_dt > 5.0) | (dRH_dt > 30.0)).astype(int)
        out.iloc[idx, out.columns.get_loc("tamper_flag")] = tamper
        
        e = (RH / 100.0) * 6.105 * np.exp((17.27 * T) / (237.7 + T))
        wbgt = 0.567 * T + 0.393 * e + 3.94
        out.iloc[idx, out.columns.get_loc("wbgt_shade")] = np.round(wbgt, 2)
        
    return out


# ── from notebook cell 184 ──
def silence_features(df, cadence_h=None, window_h=24, warn_ratio=0.5, dead_ratio=0.0):
    out = pd.DataFrame(index=df.index)
    out["comms_partial"] = 0
    out["comms_silent"] = 0
    out["silent_hours"] = 0.0
    
    if cadence_h is None:
        cadence_h = {sid: 1.0 for sid in df["station_id"].unique()}
        
    for sid, idx in df.groupby("station_id", observed=True).indices.items():
        sub_df = df.iloc[idx].copy()
        cadence = cadence_h.get(sid, 1.0)
        expected = window_h / cadence
        
        valid_obs = sub_df[["T", "P", "RH"]].notna().any(axis=1).astype(float)
        temp_df = pd.DataFrame({"timestamp": sub_df["timestamp"], "valid": valid_obs})
        observed = temp_df.rolling(window=f"{window_h}h", on="timestamp", closed="right")["valid"].sum()
        completeness = observed / expected
        
        out.iloc[idx, out.columns.get_loc("comms_partial")] = (completeness < warn_ratio).astype(int).to_numpy()
        out.iloc[idx, out.columns.get_loc("comms_silent")] = (completeness <= dead_ratio).astype(int).to_numpy()
        
        ts = sub_df["timestamp"].to_numpy()
        valid_mask = valid_obs.to_numpy().astype(bool)
        silent_h = np.zeros(len(sub_df))
        last_valid_time = None
        
        for i in range(len(sub_df)):
            if valid_mask[i]:
                last_valid_time = ts[i]
                silent_h[i] = 0.0
            else:
                if last_valid_time is not None:
                    silent_h[i] = (ts[i] - last_valid_time) / np.timedelta64(1, "h")
                else:
                    silent_h[i] = 24.0
                    
        out.iloc[idx, out.columns.get_loc("silent_hours")] = silent_h
        
    return out


# ── from notebook cell 184 ──
def build_feature_frame_final_v3(df, train_frac=1.0, station_cadence=None):
    gates = physics_gates(df, station_cadence=station_cadence)
    resid = harmonic_residuals(df, train_frac=train_frac)
    tide = tide_heartbeat(df, resid)
    cus = cusum_features_v4(resid, df)
    tel = telemetry_checks(df)
    sil = silence_features(df, cadence_h=station_cadence)
    mvar = multivariate_consistency_checks(df)
    
    F = pd.concat([gates, resid, tide, cus, tel, sil, mvar], axis=1)
    
    for ch in CHANNELS:
        r = np.full(len(df), 1.0)
        for _, idx in df.groupby("station_id", observed=True).indices.items():
            v = pd.Series(F[f"z_{ch}"].to_numpy()[idx])
            roll = v.rolling(24, min_periods=6).std().to_numpy()
            base = np.nanmedian(roll) + 1e-6
            r[idx] = np.nan_to_num(roll / base, nan=1.0)
        F[f"rollstd_ratio_{ch}"] = r
        
    FEATURES_UPDATED = (
        [f"z_{c}" for c in CHANNELS]
        + [f"d_{c}" for c in CHANNELS]
        + [f"runlen_{c}" for c in CHANNELS]
        + [f"amp_ratio_{c}" for c in CHANNELS]
        + [f"phase_dev_{c}" for c in CHANNELS]
        + [f"rollstd_ratio_{c}" for c in CHANNELS]
        + [f"cusum_fast_{c}" for c in CHANNELS]
        + [f"cusum_slow_{c}" for c in CHANNELS]
        + [f"ewma_bias_{c}" for c in CHANNELS]
        + ["dewpoint_depression", "comms_partial", "comms_silent", "silent_hours", 
           "multivar_consistency_flag", "tamper_flag"]
    )
    
    F[FEATURES_UPDATED] = F[FEATURES_UPDATED].replace([np.inf, -np.inf], np.nan)
    for ch in CHANNELS:
        F[f"amp_ratio_{ch}"] = F[f"amp_ratio_{ch}"].fillna(1.0)
    F[FEATURES_UPDATED] = F[FEATURES_UPDATED].fillna(0.0)
    return F


# ── from notebook cell 29 ──
def fit_score_models(F, train_mask, random_state=0):
    """
    Train three unsupervised detectors on a clean-ish early slice and score
    everything. Unsupervised is the honest choice: IMD has no labelled
    catalogue of past sensor failures, so a supervised model could not be
    deployed even if it scored well here.
    """
    X = F[FEATURES].to_numpy()
    scaler = StandardScaler().fit(X[train_mask])
    Xs, Xtr = scaler.transform(X), scaler.transform(X[train_mask])
    scores = {}

    iso = IsolationForest(n_estimators=300, contamination=0.02,
                          random_state=random_state).fit(Xtr)
    scores["IsolationForest"] = -iso.score_samples(Xs)

    pca = PCA(n_components=6, random_state=random_state).fit(Xtr)
    recon = pca.inverse_transform(pca.transform(Xs))
    scores["PCA-reconstruction"] = np.sqrt(((Xs - recon) ** 2).sum(axis=1))

    try:
        mcd = MinCovDet(random_state=random_state).fit(Xtr)
        scores["Mahalanobis"] = mcd.mahalanobis(Xs)
    except Exception:
        scores["Mahalanobis"] = np.zeros(len(Xs))

    return scores, {"scaler": scaler, "iso": iso, "pca": pca}


# ── from notebook cell 29 ──
def threshold_at_budget(score, alarm_budget=0.06):
    """
    Set the alarm threshold from an operational budget, never from labels.

    IMD can only dispatch so many engineers per week, so the real constraint
    is "how many alerts per day can we act on", not a tuned F1. Choosing the
    cut this way means nothing in the evaluation has seen the ground truth.
    """
    return float(np.quantile(score, 1 - alarm_budget))


# ── from notebook cell 29 ──
def threshold_at_rate(score, train_mask, target_fpr=0.01):
    return float(np.quantile(score[train_mask], 1 - target_fpr))


# ── from notebook cell 184 ──
def fuse_v3(F, ml_score, ml_threshold, degradation_cut=0.45):
    physics = F["physics_flag"].to_numpy().astype(bool)
    cusum = F["cusum_flag"].to_numpy().astype(bool)
    comms = (F["comms_error"].to_numpy().astype(bool) | 
             F["comms_silent"].to_numpy().astype(bool) | 
             F["gate_missing"].to_numpy().astype(bool) |
             (F["silent_hours"].to_numpy() > 6.0))
    ml = ml_score > ml_threshold
    degraded = F["degradation_index"].to_numpy() > degradation_cut
    
    # Regional-event veto: the SOFT layers (cusum, ml, tide) stand down when >= 2
    # neighbours share the departure. Physics gates and comms are never vetoed.
    if REGIONAL_VETO and "regional_event" in F.columns:
        regional = F["regional_event"].to_numpy().astype(bool)
        cusum, ml, degraded = cusum & ~regional, ml & ~regional, degraded & ~regional
    fused = (physics | cusum | comms | ml | degraded).astype(int)
    return fused, physics, ml, degraded, cusum, comms


# ── from notebook cell 184 ──
def classify_root_cause_final(F):
    out = np.array(["unclassified"] * len(F), dtype=object)
    
    gate_missing = F["gate_missing"].to_numpy()
    comms_silent = F["comms_silent"].to_numpy()
    silent_hours = F["silent_hours"].to_numpy()
    runlen_max = F[["runlen_T", "runlen_P", "runlen_RH"]].max(axis=1).to_numpy()
    z_max = F[["z_T", "z_P", "z_RH"]].abs().max(axis=1).to_numpy()
    d_max = F[["d_T", "d_P", "d_RH"]].max(axis=1).to_numpy()
    rollstd_max = F[["rollstd_ratio_T", "rollstd_ratio_P", "rollstd_ratio_RH"]].max(axis=1).to_numpy()
    amp_min = F[["amp_ratio_T", "amp_ratio_P", "amp_ratio_RH"]].min(axis=1).to_numpy()
    cusum_fast_max = F[["cusum_fast_T", "cusum_fast_P", "cusum_fast_RH"]].max(axis=1).to_numpy()
    cusum_slow_max = F[["cusum_slow_T", "cusum_slow_P", "cusum_slow_RH"]].max(axis=1).to_numpy()
    ewma_max = F[["ewma_bias_T", "ewma_bias_P", "ewma_bias_RH"]].abs().max(axis=1).to_numpy()
    
    for i in range(len(F)):
        if gate_missing[i] == 1 or comms_silent[i] == 1 or silent_hours[i] > 6.0:
            out[i] = "dropout"
        elif runlen_max[i] >= 6:
            out[i] = "frozen"
        elif z_max[i] > 5.0 and d_max[i] > 3.0:
            out[i] = "spike"
        elif amp_min[i] < 0.80:
            out[i] = "sluggish"
        elif rollstd_max[i] > 2.5:
            out[i] = "noise"
        elif cusum_fast_max[i] > 12.0 and ewma_max[i] > 2.5:
            out[i] = "step"
        elif cusum_slow_max[i] > 8.0:
            out[i] = "drift"
            
    return out


# ── from notebook cell 29 ──
def explain_row(F, i):
    """Per-alert evidence, ranked. This is the explainability deliverable."""
    r = F.iloc[i]
    ev = {
        "dewpoint violation":   float(r["gate_dewpoint"]),
        "out of range":         float(max(r["gate_range_T"], r["gate_range_P"], r["gate_range_RH"])),
        "frozen run length":    float(max(r["runlen_T"], r["runlen_P"], r["runlen_RH"])),
        "spatial z (T)":        float(abs(r["z_T"])),
        "spatial z (P)":        float(abs(r["z_P"])),
        "spatial z (RH)":       float(abs(r["z_RH"])),
        "variance inflation":   float(max(r["rollstd_ratio_T"], r["rollstd_ratio_P"], r["rollstd_ratio_RH"])),
        "tide amplitude loss":  float(1 - min(r["amp_ratio_T"], r["amp_ratio_P"], r["amp_ratio_RH"])),
        "cusum drift evidence": float(max(
            max(r["cusum_slow_T"], r["cusum_fast_T"]),
            max(r["cusum_slow_P"], r["cusum_fast_P"]),
            max(r["cusum_slow_RH"], r["cusum_fast_RH"])
        )),
    }
    return dict(sorted(ev.items(), key=lambda kv: -kv[1]))


# ── from notebook cell 29 ──
def impute(df, F, flag):
    """
    Repair, so the network is self-healing rather than merely self-aware.
    Estimate = the station's own harmonic signature plus the weather that
    the neighbours are simultaneously reporting.
    """
    out = df.copy()
    for ch in CHANNELS:
        est = F[f"fit_{ch}"].to_numpy().copy()
        med = (F.assign(ts=df["timestamp"].to_numpy())
                 .groupby("ts", observed=True)[f"resid_{ch}"]
                 .transform("median").to_numpy())
        est = est + np.nan_to_num(med)
        col = out[ch].to_numpy().astype(float)
        bad = (flag == 1) | ~np.isfinite(col)
        col[bad] = est[bad]
        out[f"{ch}_repaired"] = np.round(col, 2)
    return out


# ── from notebook cell 29 ──
def evaluate(df, flag, by_class=True):
    """Precision, recall, F1 and -- the metric that matters operationally --
    detection latency: how many hours the station lied before we caught it."""
    y = df["is_fault"].to_numpy()
    tp = int(((flag == 1) & (y == 1)).sum())
    fp = int(((flag == 1) & (y == 0)).sum())
    fn = int(((flag == 0) & (y == 1)).sum())
    prec = tp / (tp + fp) if tp + fp else 0.0
    rec = tp / (tp + fn) if tp + fn else 0.0
    f1 = 2 * prec * rec / (prec + rec) if prec + rec else 0.0
    overall = {"precision": prec, "recall": rec, "f1": f1,
               "false_alarm_rate": fp / max((y == 0).sum(), 1)}
    if not by_class:
        return overall

    rows = []
    for cls in sorted(set(df.loc[df["is_fault"] == 1, "fault_class"])):
        m = (df["fault_class"] == cls).to_numpy()
        r = float((flag[m] == 1).mean())
        rows.append({"fault_class": cls, "n_samples": int(m.sum()),
                     "recall": r})
    return overall, pd.DataFrame(rows)


# ── from notebook cell 124 ──
def maintenance_report(df, F, confidence, horizon_days=90, deg_threshold=0.45):
    """
    Turn detections into something an engineer can act on.

    IMD cannot dispatch a technician to a probability. What they need is a
    ranked list: which station, how bad, what kind of fault, and how long
    before it crosses the line. `days_to_threshold` extrapolates the recent
    slope of the degradation index -- a crude remaining-useful-life estimate,
    but a falsifiable one, and far more useful than an alert count.
    """
    out = []
    ts = pd.to_datetime(df["timestamp"])
    for sid, idx in df.groupby("station_id", observed=True).indices.items():
        deg = F["degradation_index"].to_numpy()[idx]
        conf = np.asarray(confidence)[idx]
        t = ts.to_numpy()[idx]
        recent = slice(max(len(idx) - 24 * horizon_days, 0), len(idx))
        dr, tr_ = deg[recent], np.arange(len(deg[recent]), dtype=float)
        ok = np.isfinite(dr)

        slope_per_day = 0.0
        if ok.sum() > 48:
            slope_per_day = float(np.polyfit(tr_[ok], dr[ok], 1)[0]) * 24.0
        cur = float(np.nanmedian(dr[ok][-72:])) if ok.sum() > 72 else float(np.nanmedian(dr[ok])) if ok.any() else 0.0

        if slope_per_day > 1e-5 and cur < deg_threshold:
            days = (deg_threshold - cur) / slope_per_day
            days_txt = int(np.clip(days, 0, 3650))
        elif cur >= deg_threshold:
            days_txt = 0
        else:
            days_txt = None

        recent_conf = conf[-168:]                      # last 7 days of hourly reports
        alerts = int((recent_conf > 0.5).sum())
        health = float(np.clip(1 - cur, 0, 1))

        out.append({
            "station_id": sid,
            "health": round(health, 3),
            "status": None,          # assigned below, relative to the network
            "degradation": round(cur, 3),
            "trend_per_day": round(slope_per_day, 5),
            "days_to_threshold": days_txt,
            "high_conf_alerts": alerts,
            "alert_rate_%": round(100 * alerts / max(len(recent_conf), 1), 2),
            "last_seen": pd.Timestamp(t[-1]),
        })
    r = pd.DataFrame(out)

    # Triage must be RELATIVE to the network, not against a fixed alert count.
    # An absolute rule ("more than 5% of samples alerted") marks every station
    # SERVICE NOW the moment the whole network is noisy, which is exactly no
    # triage at all. IMD has a finite number of engineers; the report has to
    # tell them which station to visit FIRST.
    # Floor at 1% of the week: in a quiet network the median is 0, and one stray
    # alert must not make a station 'infinitely' worse than its peers.
    med_rate = max(float(np.median(r["alert_rate_%"])), 1.0)
    r["rate_vs_network"] = (r["alert_rate_%"] / med_rate).round(2)

    def triage(row):
        if row.degradation >= deg_threshold or row.rate_vs_network >= 3.0:
            return "SERVICE NOW"
        if (row.days_to_threshold is not None
                and not pd.isna(row.days_to_threshold)
                and row.days_to_threshold < 60):
            return "SCHEDULE"
        if row.rate_vs_network >= 1.5 or row.trend_per_day > 0.001:
            return "MONITOR"
        return "OK"

    r["status"] = r.apply(triage, axis=1)
    order = {"SERVICE NOW": 0, "SCHEDULE": 1, "MONITOR": 2, "OK": 3}
    return (r.assign(_o=lambda d: d.status.map(order))
             .sort_values(["_o", "health"]).drop(columns="_o")
             .reset_index(drop=True))


# ── from notebook cell 124 ──
def impute_safe(df, F, flag, spatial_z_cut=3.0):
    """
    Repair only what the neighbours contradict.

    The earlier repair overwrote every flagged sample with a climatology-plus-
    neighbours estimate. That regressed genuine extremes toward the mean and
    pushed missed heat alerts from 130 to 205 -- the worst possible failure for
    a heatwave warning system.

    The fix is a second opinion. If a station is extreme AND its neighbours are
    extreme too, that is weather: leave it alone. Repair only when the station
    disagrees with the network, or when it broke physics outright.
    """
    out = df.copy()
    physics = F["physics_flag"].to_numpy().astype(bool)
    for ch in CHANNELS:
        est = F[f"fit_{ch}"].to_numpy().copy()
        med = (F.assign(_ts=df["timestamp"].to_numpy())
                 .groupby("_ts", observed=True)[f"resid_{ch}"]
                 .transform("median").to_numpy())
        est = est + np.nan_to_num(med)

        col = out[ch].to_numpy().astype(float)
        disagrees = np.abs(np.nan_to_num(F[f"z_{ch}"].to_numpy())) > spatial_z_cut
        repair = ((flag == 1) & (disagrees | physics)) | ~np.isfinite(col)
        col = col.copy()
        col[repair] = est[repair]
        out[f"{ch}_repaired"] = np.round(col, 2)
        out[f"{ch}_was_repaired"] = repair.astype(int)
    return out


# ── from notebook cell 184 ──
def calculate_severity(df, F, flag, rc_labels=None):
    """
    Severity = physical impact SO FAR: the largest deviation from the station's
    expected value (normalised per channel) x sqrt(hours the episode has lasted
    up to this row). Computed causally row by row, so a live stream gets the
    same number. Grades are relative to the current alert queue -- worst 20% =
    CRITICAL, next 30% = MAJOR, rest = MINOR -- so they always rank the queue
    instead of saturating.
    """
    IMPACT_SCALE = {"T": 15.0, "P": 10.0, "RH": 50.0}
    repaired_df = impute(df, F, flag)
    norm_dev = np.zeros(len(df))
    for ch in ["T", "P", "RH"]:
        d = np.abs(df[ch].to_numpy(float) - repaired_df[f"{ch}_repaired"].to_numpy(float)) / IMPACT_SCALE[ch]
        norm_dev = np.fmax(norm_dev, np.nan_to_num(d))

    is_f = np.asarray(flag) == 1
    sid = df["station_id"].to_numpy()
    new_ep = (is_f != np.r_[False, is_f[:-1]]) | (sid != np.r_[sid[:1], sid[:-1]])
    ep = np.cumsum(new_ep)

    severities = np.zeros(len(df))
    if is_f.any():
        s_ = pd.Series(norm_dev[is_f]); g_ = ep[is_f]
        dur = s_.groupby(g_).cumcount().to_numpy() + 1          # hours so far
        run = s_.groupby(g_).cummax().to_numpy()                 # worst deviation so far
        severities[is_f] = np.round(1.0 - np.exp(-run * np.sqrt(dur)), 3)

    grades = np.array(["OK"] * len(df), dtype=object)
    if is_f.any():
        q50, q80 = np.quantile(severities[is_f], [0.50, 0.80])
        grades[is_f] = np.where(severities[is_f] >= q80, "CRITICAL",
                        np.where(severities[is_f] >= q50, "MAJOR", "MINOR"))
    return severities, grades


# ── from notebook cell 184 ──
def get_confidence_scores(F, ml_score, ml_threshold):
    x = ml_score - ml_threshold
    confidence = 1.0 / (1.0 + np.exp(-3.0 * x))
    return np.round(confidence, 3)


# ── from notebook cell 184 ──
def generate_work_orders(df, F, flag, rc_labels, sev_scores, confidence):
    station_reports = []
    df_temp = df.copy()
    df_temp["flag"] = flag
    df_temp["diagnosis"] = rc_labels
    df_temp["severity"] = sev_scores
    
    for sid in df["station_id"].unique():
        sub_df = df_temp[df_temp["station_id"] == sid]
        sub_F = F[df["station_id"] == sid]
        is_active_alarm = (sub_df["flag"].iloc[-1] == 1)
        active_diagnosis = sub_df["diagnosis"].iloc[-1] if is_active_alarm else "none"
        active_severity = sub_df["severity"].iloc[-1] if is_active_alarm else 0.0
        
        recent_alarms = sub_df.tail(24 * 7)
        alarm_hours = recent_alarms["flag"].sum()
        avg_severity = recent_alarms.loc[recent_alarms["flag"] == 1, "severity"].mean() if alarm_hours > 0 else 0.0
        trust_score = max(0, 100 - int(alarm_hours * 0.25 + avg_severity * 40.0))
        
        cal_offsets = {}
        for ch in ["T", "P", "RH"]:
            final_z_bias = sub_F[f"ewma_bias_{ch}"].iloc[-1]
            resid_ch = sub_F[f"sresid_{ch}"].to_numpy()
            base_s = 1.4826 * np.nanmedian(np.abs(resid_ch - np.nanmedian(resid_ch))) + 1e-6
            cal_offsets[ch] = np.round(final_z_bias * base_s, 2)
            
        if active_diagnosis == "dropout" or active_severity >= 0.70:
            action = "SERVICE NOW (Critical Dispatch)"
        elif active_diagnosis in ["drift", "step"]:
            action = f"SCHEDULE RECALIBRATION (Offset: T={cal_offsets['T']}°C, P={cal_offsets['P']}hPa)"
        elif is_active_alarm:
            action = "MONITOR SENSOR TREND"
        else:
            action = "OK (Healthy)"
            
        station_reports.append({
            "Station ID": sid,
            "Trust Score": trust_score,
            "Active Alarm": "YES" if is_active_alarm else "NO",
            "Latest Diagnosis": active_diagnosis,
            "Latest Severity": active_severity,
            "Maintenance Action": action
        })
        
    return pd.DataFrame(station_reports)


# ── from notebook cell 186 ──
def classify_root_cause_v2(F, df):
    """
    Sahasraksha - P0-2: Two-stage, episode-level, channel-attributed classification (Fixed for Dual-CUSUM).
    """
    out_labels = np.array(["unclassified"] * len(F), dtype=object)
    
    # Find active alarm episodes
    df_temp = df.copy()
    df_temp["is_flagged"] = (
        F["comms_silent"].astype(bool)
        | F["gate_missing"].astype(bool)
        | F["physics_flag"].astype(bool)
        | F["cusum_flag"].astype(bool)
        | (F["degradation_index"] > 0.45)
    )
    
    # Grouping logic
    df_temp["episode_id"] = ((df_temp["is_flagged"] != df_temp["is_flagged"].shift()) | 
                             (df_temp["station_id"] != df_temp["station_id"].shift())).cumsum()
    
    # Process only flagged episodes
    flagged_grp = df_temp[df_temp["is_flagged"] == True].groupby("episode_id")
    
    for ep_id, grp in flagged_grp:
        indices = grp.index
        sub_F = F.loc[indices]
        sub_df = df.loc[indices]
        duration_h = len(grp)
        
        # Attribute the episode to the channel with the highest deviation/evidence
        ch_evidence = {}
        for ch in ["T", "P", "RH"]:
            # Combine Z-scores, Dual CUSUMs, and run lengths to find the culprit channel
            z_max = sub_F[f"z_{ch}"].abs().max()
            
            # Fixed: Use maximum of both fast and slow CUSUMs
            cusum_max = sub_F[[f"cusum_fast_{ch}", f"cusum_slow_{ch}"]].max(axis=1).max()
            
            runlen_max = sub_F[f"runlen_{ch}"].max()
            nan_frac = sub_df[ch].isna().mean()
            
            # Simple heuristic score for channel attribution
            ch_evidence[ch] = z_max + (cusum_max * 0.5) + (runlen_max * 0.1) + (nan_frac * 10.0)
            
        attributed_ch = max(ch_evidence, key=ch_evidence.get)
        
        # Calculate episode-level features for the attributed channel
        max_runlen = sub_F[f"runlen_{attributed_ch}"].max()
        nan_fraction = sub_df[attributed_ch].isna().mean()
        
        # Calculate onset jump and bias slope
        residuals = sub_F[f"resid_{attributed_ch}"].to_numpy()
        onset_jump = abs(residuals[0] - residuals[-1]) if len(residuals) > 1 else 0.0
        
        z_scores = sub_F[f"z_{attributed_ch}"].to_numpy()
        mean_bias = np.abs(np.nanmean(z_scores)) if len(z_scores) > 0 else 0.0
        
        # Robust linear fit of residuals vs time for bias slope
        if len(residuals) > 3:
            slope = np.polyfit(np.arange(len(residuals)), residuals, 1)[0]
        else:
            slope = 0.0
            
        # Variance ratio (rolling std compared to normal)
        var_ratio = sub_F[f"rollstd_ratio_{attributed_ch}"].max()
        
        # 2. Ordered decision rules (applied at the episode level)
        if nan_fraction > 0.5 or sub_F["silent_hours"].max() > 0:
            label = "dropout"
        elif max_runlen >= 6: # FROZEN_MIN_RUN
            label = "frozen"
        elif duration_h <= 3 and mean_bias > 3.5:
            label = "spike"
        elif (sub_F[["amp_ratio_T", "amp_ratio_P", "amp_ratio_RH"]].min(axis=1) < 0.70).mean() >= 0.40:
            label = "sluggish"
        elif (var_ratio / max(mean_bias, 0.1)) > 1.5:
            label = "noise"
        elif mean_bias > 3.0 and abs(slope) < 0.03:
            label = "step"
        elif abs(slope) >= 0.03:
            label = "drift"
        else:
            label = "unclassified"
            
        out_labels[indices] = label
        
    return out_labels


# ── from notebook cell 188 ──
def run_wmo_baseline_qc(df):
    """
    Simulates the standard operational WMO No. 8 / IMD Quality Control checks.
    Uses static gross range checks, basic consecutive step checks, and simple frozen checks.
    """
    wmo_flags = np.zeros(len(df), dtype=int)
    
    # 1. Static Gross Range Limits
    GROSS_LIMITS = {
        "T": (-40.0, 60.0),
        "P": (500.0, 1100.0),
        "RH": (0.0, 100.0)
    }
    
    # 2. Basic Step Change Limits
    STEP_LIMITS = {"T": 6.0, "P": 5.0, "RH": 45.0}
    
    # 3. Simple Frozen Threshold (Run length >= 6)
    FROZEN_LIMITS = {"T": 6, "P": 6, "RH": 10}
    
    for sid, idx in df.groupby("station_id", observed=True).indices.items():
        sub_df = df.iloc[idx]
        
        for ch in ["T", "P", "RH"]:
            arr = sub_df[ch].to_numpy()
            n = len(arr)
            
            # --- WMO Rule 1: Gross Range Check ---
            lo, hi = GROSS_LIMITS[ch]
            range_violations = (arr < lo) | (arr > hi)
            wmo_flags[idx[range_violations]] = 1
            
            # --- WMO Rule 2: Basic Step Check ---
            steps = np.abs(np.concatenate([[0.0], np.diff(arr)]))
            step_violations = steps > STEP_LIMITS[ch]
            wmo_flags[idx[step_violations]] = 1
            
            # --- WMO Rule 3: Basic Frozen Check ---
            run = np.zeros(n)
            c = 0
            for i in range(1, n):
                if not np.isnan(arr[i]) and arr[i] == arr[i-1]:
                    c += 1
                else:
                    c = 0
                run[i] = c
                
            frozen_violations = run >= FROZEN_LIMITS[ch]
            wmo_flags[idx[frozen_violations]] = 1
            
            # --- WMO Rule 4: Missing Check ---
            missing_violations = np.isnan(arr)
            wmo_flags[idx[missing_violations]] = 1
            
    return wmo_flags


# ── operator actions, from the STEP 22 cell ──
ACTIONS = {
    "impossible": "Quarantine this reading from forecast assimilation and substitute the estimate below. "
                  "If it recurs within 24 h, dispatch a technician to inspect the T/RH probe and radiation shield.",
    "corrupt":    "Record failed an integrity check (duplicate or out-of-order timestamp, or a unit/format error). "
                  "Reject at ingest; check the logger clock and transmission format.",
    "spike":      "Quarantine the single reading and substitute the estimate. No dispatch unless it recurs.",
    "frozen":     "Sensor or logger stuck. Power-cycle the logger remotely; dispatch if not cleared in 6 h.",
    "dropout":    "Communication failure. Check telemetry link and power; values shown are estimates until the link returns.",
    "drift":      "Calibration drift. Schedule recalibration against a transfer standard; apply the offset meanwhile.",
    "step":       "Bias offset (post-maintenance / resiting). Verify installation and apply the offset.",
    "noise":      "Noisy signal. Inspect wiring, ADC and moisture ingress.",
    "sluggish":   "Damped response. Clean the hygrometer, clear the pressure port, check the radiation shield.",
    "unclassified": "Review manually.",
}

fuse = fuse_v3   # notebook cell 29 alias; the real-data cells call fuse()
